export enum ProposalActionEnum {
  ASSIGN_USERS = 'ASSIGN_USERS',
  FINANCE_TABLE_ITEM_CREATED = 'FINANCE_TABLE_ITEM_CREATED',
  FINANCE_TABLE_ITEM_UPDATED = 'FINANCE_TABLE_ITEM_UPDATED',
  FINANCE_TABLE_ITEM_DELETED = 'FINANCE_TABLE_ITEM_DELETED',
  FINANCE_TABLE_CREATED = 'FINANCE_TABLE_CREATED',
  FINANCE_TABLE_UPDATED = 'FINANCE_TABLE_UPDATED',
  FINANCE_TABLE_DELETED = 'FINANCE_TABLE_DELETED',
  PROPOSAL_CONTENT_CREATED = 'PROPOSAL_CONTENT_CREATED',
  PROPOSAL_CONTENT_UPDATED = 'PROPOSAL_CONTENT_UPDATED ',
  PROPOSAL_CONTENT_DELETED = 'PROPOSAL_CONTENT_DELETED',
  PROPOSAL_CREATED = 'PROPOSAL_CREATED',
  PROPOSAL_UPDATED = 'PROPOSAL_UPDATED ',
  PROPOSAL_DELETED = 'PROPOSAL_DELETED',
  PROPOSAL_REJECTED = 'PROPOSAL_REJECTED',
  PROPOSAL_WAITING_APPROVAL = 'PROPOSAL_WAITING_APPROVAL',
  PROPOSAL_APPROVED = 'PROPOSAL_APPROVED',
  PROPOSAL_USERS_UPDATED = 'PROPOSAL_USERS_UPDATED'
}
