export enum NotificationTypeEnums {
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  OPPORTUNITY_ASSIGNED = 'OPPORTUNITY_ASSIGNED',
  DEAL_ASSIGNED = 'DEAL_ASSIGNED',
  DEAL_WON = 'DEAL_WON',
  PROJECT_ASSIGNED = 'PROJECT_ASSIGNED',
  CLIENT_ASSIGNED = 'CLIENT_ASSIGNED',
  PROPOSAL_APPROVED = 'PROPOSAL_APPROVED',
  PROPOSAL_REJECTED = 'PROPOSAL_REJECTED',
  PROPOSAL_ASSIGNED = 'PROPOSAL_ASSIGNED',
  TASK_DUE = 'TASK_DUE',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  COMMENT_MENTION = 'COMMENT_MENTION',
  WORKFLOW_TRIGGERED = 'WORKFLOW_TRIGGERED',
  SLA_BREACH = 'SLA_BREACH',
  SLA_WARNING = 'SLA_WARNING',
  INVOICE_OVERDUE = 'INVOICE_OVERDUE',
  CONTRACT_EXPIRING = 'CONTRACT_EXPIRING',
  SYSTEM_ALERT = 'SYSTEM_ALERT'
}

export enum NotificationReadEnums {
  READ = 'READ',
  UN_READ = 'UN_READ',
  CLICKED = 'CLICKED'
}
