export enum NotificationTypeEnums {
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  OPPORTUNITY_ASSIGNED = 'OPPORTUNITY_ASSIGNED',
  DEAL_ASSIGNED = 'DEAL_ASSIGNED',
  PROJECT_ASSIGNED = 'PROJECT_ASSIGNED',
  CLIENT_ASSIGNED = 'CLIENT_ASSIGNED',
  PROPOSAL_APPROVED = 'PROPOSAL_APPROVED',
  PROPOSAL_REJECTED = 'PROPOSAL_REJECTED',
  PROPOSAL_ASSIGNED = 'PROPOSAL_ASSIGNED'
}

export enum NotificationReadEnums {
  READ = 'READ',
  UN_READ = 'UN_READ',
  CLICKED = 'CLICKED'
}
