/**
 * Simple template engine for document builder.
 * Supports: {{variable}}, {{#if condition}}...{{/if}}, {{#each items}}...{{/each}}
 */

interface BrandSettings {
  companyName?: string;
  logo?: string;
  primaryColor?: string;
  accentColor?: string;
  fontFamily?: string;
  companyAddress?: string;
  companyPhone?: string;
  companyEmail?: string;
  companyTaxId?: string;
  brandFooterText?: string;
}

/**
 * Resolve a dotted path like "item.name" from a data object.
 */
function resolvePath(obj: Record<string, any>, path: string): any {
  return path.split('.').reduce((acc, key) => (acc != null ? acc[key] : undefined), obj);
}

/**
 * Escape HTML entities to prevent XSS.
 */
function escapeHtml(str: string): string {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Process {{#each items}}...{{/each}} blocks.
 * Inside the block, {{this.field}} or {{field}} references the current item.
 * {{@index}} gives the 0-based index, {{@number}} gives 1-based.
 */
function processEachBlocks(template: string, data: Record<string, any>): string {
  const eachRegex = /\{\{#each\s+(\w+(?:\.\w+)*)\}\}([\s\S]*?)\{\{\/each\}\}/g;

  return template.replace(eachRegex, (_match, arrayPath: string, body: string) => {
    const items = resolvePath(data, arrayPath);
    if (!Array.isArray(items) || items.length === 0) return '';

    return items
      .map((item, index) => {
        // Create a context where item fields are accessible directly and via "this."
        let rendered = body;
        // Replace {{@index}} and {{@number}}
        rendered = rendered.replace(/\{\{@index\}\}/g, String(index));
        rendered = rendered.replace(/\{\{@number\}\}/g, String(index + 1));

        // Replace {{this.field}} with item.field
        rendered = rendered.replace(/\{\{this\.(\w+(?:\.\w+)*)\}\}/g, (_m: string, field: string) => {
          const val = resolvePath(item, field);
          return val != null ? escapeHtml(String(val)) : '';
        });

        // Replace {{field}} that matches item keys (scoped to current item)
        if (typeof item === 'object' && item !== null) {
          for (const key of Object.keys(item)) {
            const regex = new RegExp(`\\{\\{${key}\\}\\}`, 'g');
            rendered = rendered.replace(regex, item[key] != null ? escapeHtml(String(item[key])) : '');
          }
        }

        return rendered;
      })
      .join('');
  });
}

/**
 * Process {{#if condition}}...{{else}}...{{/if}} blocks.
 * condition is truthy check on the data value.
 */
function processIfBlocks(template: string, data: Record<string, any>): string {
  // Handle if/else
  const ifElseRegex = /\{\{#if\s+(\w+(?:\.\w+)*)\}\}([\s\S]*?)\{\{else\}\}([\s\S]*?)\{\{\/if\}\}/g;
  let result = template.replace(ifElseRegex, (_match, condition: string, trueBlock: string, falseBlock: string) => {
    const value = resolvePath(data, condition);
    return value ? trueBlock : falseBlock;
  });

  // Handle if without else
  const ifRegex = /\{\{#if\s+(\w+(?:\.\w+)*)\}\}([\s\S]*?)\{\{\/if\}\}/g;
  result = result.replace(ifRegex, (_match, condition: string, block: string) => {
    const value = resolvePath(data, condition);
    return value ? block : '';
  });

  return result;
}

/**
 * Replace simple {{variable}} placeholders with data values.
 */
function replaceVariables(template: string, data: Record<string, any>): string {
  return template.replace(/\{\{(\w+(?:\.\w+)*)\}\}/g, (_match, path: string) => {
    const val = resolvePath(data, path);
    return val != null ? escapeHtml(String(val)) : '';
  });
}

/**
 * Main render function: processes a template string with data and brand settings.
 *
 * Processing order:
 * 1. Inject brand settings as {{brand.*}} variables
 * 2. Process {{#each}} blocks
 * 3. Process {{#if}} blocks
 * 4. Replace {{variable}} placeholders
 */
export function renderTemplate(template: string, data: Record<string, any>, brand?: BrandSettings): string {
  // Merge brand settings into data under "brand" namespace
  const mergedData: Record<string, any> = {
    ...data,
    brand: {
      companyName: brand?.companyName || data.companyName || '',
      logo: brand?.logo || '',
      primaryColor: brand?.primaryColor || '#7c3aed',
      accentColor: brand?.accentColor || '#a855f7',
      fontFamily: brand?.fontFamily || "'Segoe UI', system-ui, sans-serif",
      companyAddress: brand?.companyAddress || data.companyAddress || '',
      companyPhone: brand?.companyPhone || data.companyPhone || '',
      companyEmail: brand?.companyEmail || data.companyEmail || '',
      companyTaxId: brand?.companyTaxId || data.companyTaxId || '',
      footerText: brand?.brandFooterText || 'Generated by Leadify CRM'
    }
  };

  let result = template;
  result = processEachBlocks(result, mergedData);
  result = processIfBlocks(result, mergedData);
  result = replaceVariables(result, mergedData);

  return result;
}

/**
 * Render a full document using a DocumentTemplate layout + content data + brand settings.
 * The template layout contains an HTML string with {{placeholders}}.
 */
export function renderFromTemplate(
  templateHtml: string,
  content: Record<string, any>,
  brand?: BrandSettings
): string {
  // Parse items financial data if present
  const items = content.items || [];
  const currency = content.currency || 'SAR';
  const subtotal = items.reduce((sum: number, item: any) => sum + (item.quantity || 0) * (item.rate || 0), 0);
  const discountAmount =
    content.discountType === 'percent' ? subtotal * ((content.discount || 0) / 100) : content.discount || 0;
  const taxableAmount = subtotal - discountAmount;
  const taxAmount = taxableAmount * ((content.taxRate || 0) / 100);
  const total = taxableAmount + taxAmount;

  const enrichedContent = {
    ...content,
    currency,
    subtotal: subtotal.toFixed(2),
    discountAmount: discountAmount.toFixed(2),
    taxAmount: taxAmount.toFixed(2),
    total: total.toFixed(2),
    hasDiscount: discountAmount > 0,
    hasTax: (content.taxRate || 0) > 0,
    hasItems: items.length > 0,
    hasBank: !!content.bankName,
    hasPaymentTerms: !!content.paymentTerms,
    hasTerms: !!content.termsAndConditions,
    hasNotes: !!content.notes,
    // Format dates
    formattedDate: content.date ? new Date(content.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '',
    formattedDueDate: content.dueDate ? new Date(content.dueDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '',
    formattedValidUntil: content.validUntil ? new Date(content.validUntil).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '',
    // Enrich items with computed lineTotal
    items: items.map((item: any, i: number) => ({
      ...item,
      index: i + 1,
      lineTotal: ((item.quantity || 0) * (item.rate || 0)).toFixed(2)
    }))
  };

  return renderTemplate(templateHtml, enrichedContent, brand);
}

export type { BrandSettings };
