@echo off
echo KILLING OLD PROCESSES...
taskkill /F /IM node.exe >nul 2>&1

echo STARTING PM2 ECOSYSTEM...
call npx pm2 start ecosystem.config.js

echo OPENING BROWSER...
start http://localhost:3060

echo OPENING MONITOR...
call npx pm2 monit
