export enum CustomFieldType {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  SELECT = 'SELECT',
  MULTISELECT = 'MULTISELECT',
  CHECKBOX = 'CHECKBOX',
  TEXTAREA = 'TEXTAREA',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  URL = 'URL',
  CURRENCY = 'CURRENCY'
}

export enum CustomFieldEntity {
  LEAD = 'LEAD',
  DEAL = 'DEAL',
  OPPORTUNITY = 'OPPORTUNITY',
  CLIENT = 'CLIENT',
  CONTACT = 'CONTACT',
  INVOICE = 'INVOICE'
}
